version: '3.9'

services:
  db:
    container_name: db
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=rent_car
      - POSTGRES_PASSWORD=root
    image: postgres:latest
    networks:
      - backend

  app:
    container_name: app
    image: fausberg/rentcar:v4
    ports:
    - "8080:8080"
    environment:
     - DB_HOST=db
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge


